// Auto-generated by: pnpm db:gen-types
// Run `supabase gen types typescript --local` to regenerate
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
